# site settings
title: LabCívico
email: prensa@ciudadanointeligente.org
description: 'Experimientos ciudadanos para el cambio social en la región'
baseurl: '//labcivico.org' #"//ciudadanointeligente.github.io/labcivico/"
basedomain: labcivico.org
analytics: 'UA-41822715-8'

# build settings
markdown: kramdown

collections:
  projectcards:
    output: true
  team:
    output: true
  projectteam01:
    output: true
  projectteam02:
    output: true